package Java.mohamedproject.Enums;

public enum Departments {

    ADMINISTRATION,
    RECEPTION,
    EMERGENCY_ROOM,
    CARDIOLOGY,
    PEDIATRICS,
    ORTHOPEDICS,
    DERMATOLOGY,
    NEUROLOGY,
    ONCOLOGY,
    EAR_NOSE_THROAT,
    OPHTHALMOLOGY,
    GASTROENTEROLOGY,
    GENERAL_SURGERY,
    INTERNAL_MEDICINE,
    UROLOGY,
    GYNECOLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    PSYCHIATRY,
    PHYSIOTHERAPY,
    INTENSIVE_CARE_UNIT,
    LABORATORY

}
