@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1258113742 { 
   	label=Employee
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Employee1258113742[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Employee</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   experienceYears: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   salary: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   workHours: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1585103185 { 
   	label=Reception
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Reception1585103185[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Reception</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   numberOfPatients: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   patients: ArrayList&lt;Patient&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPatient(patient: Patient)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1907849355 { 
   	label=Person
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Person1907849355[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Person</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   personalInformation: PersonalInformation [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2052357439 { 
   	label=Doctor
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Doctor2052357439[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Doctor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   department: Department [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_253715302 { 
   	label=Administrators
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Administrators253715302[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Administrators</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   doctors: ArrayList&lt;Doctor&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numberOfDoctorsAdded: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numberOfNursesAdded: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nurses: ArrayList&lt;Nurse&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addDoctor(doctor: Doctor)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addNurse(nurse: Nurse)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_75633405 { 
   	label=Nurse
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Nurse75633405[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Nurse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   department: Department [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_873235173 { 
   	label=Patient
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Patient873235173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Patient</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bloodType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   disease: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Employee1258113742 -> Administrators253715302[arrowhead=none, arrowtail=empty, dir=both];
Employee1258113742 -> Doctor2052357439[arrowhead=none, arrowtail=empty, dir=both];
Employee1258113742 -> Nurse75633405[arrowhead=none, arrowtail=empty, dir=both];
Employee1258113742 -> Reception1585103185[arrowhead=none, arrowtail=empty, dir=both];
Main2390489 -> Reception1585103185[label="main() -> addPatient()"];
Person1907849355 -> Employee1258113742[arrowhead=none, arrowtail=empty, dir=both];
Person1907849355 -> Patient873235173[arrowhead=none, arrowtail=empty, dir=both];
Reception1585103185 -> Patient873235173[label="patients
[0..*]"];
    
}
@enduml